/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainClientRouteImport } from './routes/_main/_client'
import { Route as MainAuthenticatedRouteImport } from './routes/_main/_authenticated'
import { Route as MainSplatRouteImport } from './routes/_main/$'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as MainClientIndexRouteImport } from './routes/_main/_client/index'
import { Route as MainAuthenticatedAdminDashboardRouteImport } from './routes/_main/_authenticated/admin/dashboard'
import { Route as MainAuthenticatedAdminUsersViewRouteImport } from './routes/_main/_authenticated/admin/users/view'
import { Route as MainAuthenticatedAdminUsersManagementRouteImport } from './routes/_main/_authenticated/admin/users/management'
import { Route as MainAuthenticatedAdminSecurityLoginLogsRouteImport } from './routes/_main/_authenticated/admin/security/login-logs'
import { Route as MainAuthenticatedAdminSecurityActionLogsRouteImport } from './routes/_main/_authenticated/admin/security/action-logs'
import { Route as MainAuthenticatedAdminCatalogType_managementRouteImport } from './routes/_main/_authenticated/admin/catalog/type_management'
import { Route as MainAuthenticatedAdminCatalogProduct_viewRouteImport } from './routes/_main/_authenticated/admin/catalog/product_view'
import { Route as MainAuthenticatedAdminCatalogProduct_managementRouteImport } from './routes/_main/_authenticated/admin/catalog/product_management'
import { Route as MainAuthenticatedAdminCatalogColor_managementRouteImport } from './routes/_main/_authenticated/admin/catalog/color_management'
import { Route as MainAuthenticatedAdminCatalogCategories_managementRouteImport } from './routes/_main/_authenticated/admin/catalog/categories_management'
import { Route as MainAuthenticatedAdminCatalogBrands_managementRouteImport } from './routes/_main/_authenticated/admin/catalog/brands_management'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainClientRoute = MainClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => MainRoute,
} as any)
const MainAuthenticatedRoute = MainAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => MainRoute,
} as any)
const MainSplatRoute = MainSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MainRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainClientIndexRoute = MainClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainClientRoute,
} as any)
const MainAuthenticatedAdminDashboardRoute =
  MainAuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminUsersViewRoute =
  MainAuthenticatedAdminUsersViewRouteImport.update({
    id: '/admin/users/view',
    path: '/admin/users/view',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminUsersManagementRoute =
  MainAuthenticatedAdminUsersManagementRouteImport.update({
    id: '/admin/users/management',
    path: '/admin/users/management',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminSecurityLoginLogsRoute =
  MainAuthenticatedAdminSecurityLoginLogsRouteImport.update({
    id: '/admin/security/login-logs',
    path: '/admin/security/login-logs',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminSecurityActionLogsRoute =
  MainAuthenticatedAdminSecurityActionLogsRouteImport.update({
    id: '/admin/security/action-logs',
    path: '/admin/security/action-logs',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminCatalogType_managementRoute =
  MainAuthenticatedAdminCatalogType_managementRouteImport.update({
    id: '/admin/catalog/type_management',
    path: '/admin/catalog/type_management',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminCatalogProduct_viewRoute =
  MainAuthenticatedAdminCatalogProduct_viewRouteImport.update({
    id: '/admin/catalog/product_view',
    path: '/admin/catalog/product_view',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminCatalogProduct_managementRoute =
  MainAuthenticatedAdminCatalogProduct_managementRouteImport.update({
    id: '/admin/catalog/product_management',
    path: '/admin/catalog/product_management',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminCatalogColor_managementRoute =
  MainAuthenticatedAdminCatalogColor_managementRouteImport.update({
    id: '/admin/catalog/color_management',
    path: '/admin/catalog/color_management',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminCatalogCategories_managementRoute =
  MainAuthenticatedAdminCatalogCategories_managementRouteImport.update({
    id: '/admin/catalog/categories_management',
    path: '/admin/catalog/categories_management',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)
const MainAuthenticatedAdminCatalogBrands_managementRoute =
  MainAuthenticatedAdminCatalogBrands_managementRouteImport.update({
    id: '/admin/catalog/brands_management',
    path: '/admin/catalog/brands_management',
    getParentRoute: () => MainAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainClientIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/$': typeof MainSplatRoute
  '/admin/dashboard': typeof MainAuthenticatedAdminDashboardRoute
  '/admin/catalog/brands_management': typeof MainAuthenticatedAdminCatalogBrands_managementRoute
  '/admin/catalog/categories_management': typeof MainAuthenticatedAdminCatalogCategories_managementRoute
  '/admin/catalog/color_management': typeof MainAuthenticatedAdminCatalogColor_managementRoute
  '/admin/catalog/product_management': typeof MainAuthenticatedAdminCatalogProduct_managementRoute
  '/admin/catalog/product_view': typeof MainAuthenticatedAdminCatalogProduct_viewRoute
  '/admin/catalog/type_management': typeof MainAuthenticatedAdminCatalogType_managementRoute
  '/admin/security/action-logs': typeof MainAuthenticatedAdminSecurityActionLogsRoute
  '/admin/security/login-logs': typeof MainAuthenticatedAdminSecurityLoginLogsRoute
  '/admin/users/management': typeof MainAuthenticatedAdminUsersManagementRoute
  '/admin/users/view': typeof MainAuthenticatedAdminUsersViewRoute
}
export interface FileRoutesByTo {
  '/': typeof MainClientIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/$': typeof MainSplatRoute
  '/admin/dashboard': typeof MainAuthenticatedAdminDashboardRoute
  '/admin/catalog/brands_management': typeof MainAuthenticatedAdminCatalogBrands_managementRoute
  '/admin/catalog/categories_management': typeof MainAuthenticatedAdminCatalogCategories_managementRoute
  '/admin/catalog/color_management': typeof MainAuthenticatedAdminCatalogColor_managementRoute
  '/admin/catalog/product_management': typeof MainAuthenticatedAdminCatalogProduct_managementRoute
  '/admin/catalog/product_view': typeof MainAuthenticatedAdminCatalogProduct_viewRoute
  '/admin/catalog/type_management': typeof MainAuthenticatedAdminCatalogType_managementRoute
  '/admin/security/action-logs': typeof MainAuthenticatedAdminSecurityActionLogsRoute
  '/admin/security/login-logs': typeof MainAuthenticatedAdminSecurityLoginLogsRoute
  '/admin/users/management': typeof MainAuthenticatedAdminUsersManagementRoute
  '/admin/users/view': typeof MainAuthenticatedAdminUsersViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_main/$': typeof MainSplatRoute
  '/_main/_authenticated': typeof MainAuthenticatedRouteWithChildren
  '/_main/_client': typeof MainClientRouteWithChildren
  '/_main/_client/': typeof MainClientIndexRoute
  '/_main/_authenticated/admin/dashboard': typeof MainAuthenticatedAdminDashboardRoute
  '/_main/_authenticated/admin/catalog/brands_management': typeof MainAuthenticatedAdminCatalogBrands_managementRoute
  '/_main/_authenticated/admin/catalog/categories_management': typeof MainAuthenticatedAdminCatalogCategories_managementRoute
  '/_main/_authenticated/admin/catalog/color_management': typeof MainAuthenticatedAdminCatalogColor_managementRoute
  '/_main/_authenticated/admin/catalog/product_management': typeof MainAuthenticatedAdminCatalogProduct_managementRoute
  '/_main/_authenticated/admin/catalog/product_view': typeof MainAuthenticatedAdminCatalogProduct_viewRoute
  '/_main/_authenticated/admin/catalog/type_management': typeof MainAuthenticatedAdminCatalogType_managementRoute
  '/_main/_authenticated/admin/security/action-logs': typeof MainAuthenticatedAdminSecurityActionLogsRoute
  '/_main/_authenticated/admin/security/login-logs': typeof MainAuthenticatedAdminSecurityLoginLogsRoute
  '/_main/_authenticated/admin/users/management': typeof MainAuthenticatedAdminUsersManagementRoute
  '/_main/_authenticated/admin/users/view': typeof MainAuthenticatedAdminUsersViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/$'
    | '/admin/dashboard'
    | '/admin/catalog/brands_management'
    | '/admin/catalog/categories_management'
    | '/admin/catalog/color_management'
    | '/admin/catalog/product_management'
    | '/admin/catalog/product_view'
    | '/admin/catalog/type_management'
    | '/admin/security/action-logs'
    | '/admin/security/login-logs'
    | '/admin/users/management'
    | '/admin/users/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/$'
    | '/admin/dashboard'
    | '/admin/catalog/brands_management'
    | '/admin/catalog/categories_management'
    | '/admin/catalog/color_management'
    | '/admin/catalog/product_management'
    | '/admin/catalog/product_view'
    | '/admin/catalog/type_management'
    | '/admin/security/action-logs'
    | '/admin/security/login-logs'
    | '/admin/users/management'
    | '/admin/users/view'
  id:
    | '__root__'
    | '/_main'
    | '/_auth/login'
    | '/_auth/register'
    | '/_main/$'
    | '/_main/_authenticated'
    | '/_main/_client'
    | '/_main/_client/'
    | '/_main/_authenticated/admin/dashboard'
    | '/_main/_authenticated/admin/catalog/brands_management'
    | '/_main/_authenticated/admin/catalog/categories_management'
    | '/_main/_authenticated/admin/catalog/color_management'
    | '/_main/_authenticated/admin/catalog/product_management'
    | '/_main/_authenticated/admin/catalog/product_view'
    | '/_main/_authenticated/admin/catalog/type_management'
    | '/_main/_authenticated/admin/security/action-logs'
    | '/_main/_authenticated/admin/security/login-logs'
    | '/_main/_authenticated/admin/users/management'
    | '/_main/_authenticated/admin/users/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_client': {
      id: '/_main/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainClientRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_authenticated': {
      id: '/_main/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainAuthenticatedRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$': {
      id: '/_main/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof MainSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_client/': {
      id: '/_main/_client/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainClientIndexRouteImport
      parentRoute: typeof MainClientRoute
    }
    '/_main/_authenticated/admin/dashboard': {
      id: '/_main/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof MainAuthenticatedAdminDashboardRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/users/view': {
      id: '/_main/_authenticated/admin/users/view'
      path: '/admin/users/view'
      fullPath: '/admin/users/view'
      preLoaderRoute: typeof MainAuthenticatedAdminUsersViewRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/users/management': {
      id: '/_main/_authenticated/admin/users/management'
      path: '/admin/users/management'
      fullPath: '/admin/users/management'
      preLoaderRoute: typeof MainAuthenticatedAdminUsersManagementRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/security/login-logs': {
      id: '/_main/_authenticated/admin/security/login-logs'
      path: '/admin/security/login-logs'
      fullPath: '/admin/security/login-logs'
      preLoaderRoute: typeof MainAuthenticatedAdminSecurityLoginLogsRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/security/action-logs': {
      id: '/_main/_authenticated/admin/security/action-logs'
      path: '/admin/security/action-logs'
      fullPath: '/admin/security/action-logs'
      preLoaderRoute: typeof MainAuthenticatedAdminSecurityActionLogsRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/catalog/type_management': {
      id: '/_main/_authenticated/admin/catalog/type_management'
      path: '/admin/catalog/type_management'
      fullPath: '/admin/catalog/type_management'
      preLoaderRoute: typeof MainAuthenticatedAdminCatalogType_managementRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/catalog/product_view': {
      id: '/_main/_authenticated/admin/catalog/product_view'
      path: '/admin/catalog/product_view'
      fullPath: '/admin/catalog/product_view'
      preLoaderRoute: typeof MainAuthenticatedAdminCatalogProduct_viewRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/catalog/product_management': {
      id: '/_main/_authenticated/admin/catalog/product_management'
      path: '/admin/catalog/product_management'
      fullPath: '/admin/catalog/product_management'
      preLoaderRoute: typeof MainAuthenticatedAdminCatalogProduct_managementRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/catalog/color_management': {
      id: '/_main/_authenticated/admin/catalog/color_management'
      path: '/admin/catalog/color_management'
      fullPath: '/admin/catalog/color_management'
      preLoaderRoute: typeof MainAuthenticatedAdminCatalogColor_managementRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/catalog/categories_management': {
      id: '/_main/_authenticated/admin/catalog/categories_management'
      path: '/admin/catalog/categories_management'
      fullPath: '/admin/catalog/categories_management'
      preLoaderRoute: typeof MainAuthenticatedAdminCatalogCategories_managementRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
    '/_main/_authenticated/admin/catalog/brands_management': {
      id: '/_main/_authenticated/admin/catalog/brands_management'
      path: '/admin/catalog/brands_management'
      fullPath: '/admin/catalog/brands_management'
      preLoaderRoute: typeof MainAuthenticatedAdminCatalogBrands_managementRouteImport
      parentRoute: typeof MainAuthenticatedRoute
    }
  }
}

interface MainAuthenticatedRouteChildren {
  MainAuthenticatedAdminDashboardRoute: typeof MainAuthenticatedAdminDashboardRoute
  MainAuthenticatedAdminCatalogBrands_managementRoute: typeof MainAuthenticatedAdminCatalogBrands_managementRoute
  MainAuthenticatedAdminCatalogCategories_managementRoute: typeof MainAuthenticatedAdminCatalogCategories_managementRoute
  MainAuthenticatedAdminCatalogColor_managementRoute: typeof MainAuthenticatedAdminCatalogColor_managementRoute
  MainAuthenticatedAdminCatalogProduct_managementRoute: typeof MainAuthenticatedAdminCatalogProduct_managementRoute
  MainAuthenticatedAdminCatalogProduct_viewRoute: typeof MainAuthenticatedAdminCatalogProduct_viewRoute
  MainAuthenticatedAdminCatalogType_managementRoute: typeof MainAuthenticatedAdminCatalogType_managementRoute
  MainAuthenticatedAdminSecurityActionLogsRoute: typeof MainAuthenticatedAdminSecurityActionLogsRoute
  MainAuthenticatedAdminSecurityLoginLogsRoute: typeof MainAuthenticatedAdminSecurityLoginLogsRoute
  MainAuthenticatedAdminUsersManagementRoute: typeof MainAuthenticatedAdminUsersManagementRoute
  MainAuthenticatedAdminUsersViewRoute: typeof MainAuthenticatedAdminUsersViewRoute
}

const MainAuthenticatedRouteChildren: MainAuthenticatedRouteChildren = {
  MainAuthenticatedAdminDashboardRoute: MainAuthenticatedAdminDashboardRoute,
  MainAuthenticatedAdminCatalogBrands_managementRoute:
    MainAuthenticatedAdminCatalogBrands_managementRoute,
  MainAuthenticatedAdminCatalogCategories_managementRoute:
    MainAuthenticatedAdminCatalogCategories_managementRoute,
  MainAuthenticatedAdminCatalogColor_managementRoute:
    MainAuthenticatedAdminCatalogColor_managementRoute,
  MainAuthenticatedAdminCatalogProduct_managementRoute:
    MainAuthenticatedAdminCatalogProduct_managementRoute,
  MainAuthenticatedAdminCatalogProduct_viewRoute:
    MainAuthenticatedAdminCatalogProduct_viewRoute,
  MainAuthenticatedAdminCatalogType_managementRoute:
    MainAuthenticatedAdminCatalogType_managementRoute,
  MainAuthenticatedAdminSecurityActionLogsRoute:
    MainAuthenticatedAdminSecurityActionLogsRoute,
  MainAuthenticatedAdminSecurityLoginLogsRoute:
    MainAuthenticatedAdminSecurityLoginLogsRoute,
  MainAuthenticatedAdminUsersManagementRoute:
    MainAuthenticatedAdminUsersManagementRoute,
  MainAuthenticatedAdminUsersViewRoute: MainAuthenticatedAdminUsersViewRoute,
}

const MainAuthenticatedRouteWithChildren =
  MainAuthenticatedRoute._addFileChildren(MainAuthenticatedRouteChildren)

interface MainClientRouteChildren {
  MainClientIndexRoute: typeof MainClientIndexRoute
}

const MainClientRouteChildren: MainClientRouteChildren = {
  MainClientIndexRoute: MainClientIndexRoute,
}

const MainClientRouteWithChildren = MainClientRoute._addFileChildren(
  MainClientRouteChildren,
)

interface MainRouteChildren {
  MainSplatRoute: typeof MainSplatRoute
  MainAuthenticatedRoute: typeof MainAuthenticatedRouteWithChildren
  MainClientRoute: typeof MainClientRouteWithChildren
}

const MainRouteChildren: MainRouteChildren = {
  MainSplatRoute: MainSplatRoute,
  MainAuthenticatedRoute: MainAuthenticatedRouteWithChildren,
  MainClientRoute: MainClientRouteWithChildren,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
